version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: America/Chicago
    open-pull-requests-limit: 10
    groups:
      microsoft-codeanalysis:
        patterns:
          - "Microsoft.CodeAnalysis*"
      aspire:
        patterns:
          - "Aspire*"
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions*"
      test-dependencies:
        patterns:
          - "AwesomeAssertions"
          - "MSTest*"
          - "Microsoft.Testing*"
          - "NSubstitute"
      dotnet-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: America/Chicago
    open-pull-requests-limit: 10
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
