<Project>
  <Import Project="$(MSBuildThisFileDirectory)eng\Version.props"
          Condition="Exists('$(MSBuildThisFileDirectory)eng\Version.props')" />

  <PropertyGroup>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <IsPackable>false</IsPackable>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
