<Project Sdk="MSTest.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\AmbientContext.Abstractions\AmbientContext.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\AmbientContext.Core\AmbientContext.Core.csproj" />
    <ProjectReference Include="..\..\src\AmbientContext.Analyzers\AmbientContext.Analyzers.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <ProjectReference Include="..\..\src\AmbientContext.Analyzers\AmbientContext.Analyzers.csproj" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
</Project>
