<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AmbientContext.Abstractions\AmbientContext.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\AmbientContext.Core\AmbientContext.Core.csproj" />
    <ProjectReference Include="..\..\src\AmbientContext.Generators\AmbientContext.Generators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
